//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package android.support.constraint;

import com.zqy.google.android.ResourcesUtil;
import com.zqy.google.android.StyleaUtils;

public final class R {
    public R() {
    }

    public static final class styleable {
        public static final int[] ConstraintLayout_Layout;
        public static final int ConstraintLayout_Layout_android_maxHeight;
        public static final int ConstraintLayout_Layout_android_maxWidth;
        public static final int ConstraintLayout_Layout_android_minHeight;
        public static final int ConstraintLayout_Layout_android_minWidth;
        public static final int ConstraintLayout_Layout_android_orientation;
        public static final int ConstraintLayout_Layout_barrierAllowsGoneWidgets;
        public static final int ConstraintLayout_Layout_barrierDirection;
        public static final int ConstraintLayout_Layout_chainUseRtl;
        public static final int ConstraintLayout_Layout_constraintSet;
        public static final int ConstraintLayout_Layout_constraint_referenced_ids;
        public static final int ConstraintLayout_Layout_layout_constrainedHeight;
        public static final int ConstraintLayout_Layout_layout_constrainedWidth;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_creator;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_creator;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toTopOf;
        public static final int ConstraintLayout_Layout_layout_constraintCircle;
        public static final int ConstraintLayout_Layout_layout_constraintCircleAngle;
        public static final int ConstraintLayout_Layout_layout_constraintCircleRadius;
        public static final int ConstraintLayout_Layout_layout_constraintDimensionRatio;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toEndOf;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toStartOf;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_begin;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_end;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_percent;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_default;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_max;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_min;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_percent;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_bias;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_weight;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_creator;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toRightOf;
        public static final int ConstraintLayout_Layout_layout_constraintRight_creator;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toLeftOf;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toRightOf;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toEndOf;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toStartOf;
        public static final int ConstraintLayout_Layout_layout_constraintTop_creator;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toBottomOf;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toTopOf;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_bias;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_chainStyle;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_weight;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_default;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_max;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_min;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_percent;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteX;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteY;
        public static final int ConstraintLayout_Layout_layout_goneMarginBottom;
        public static final int ConstraintLayout_Layout_layout_goneMarginEnd;
        public static final int ConstraintLayout_Layout_layout_goneMarginLeft;
        public static final int ConstraintLayout_Layout_layout_goneMarginRight;
        public static final int ConstraintLayout_Layout_layout_goneMarginStart;
        public static final int ConstraintLayout_Layout_layout_goneMarginTop;
        public static final int ConstraintLayout_Layout_layout_optimizationLevel;
        public static final int[] ConstraintLayout_placeholder;
        public static final int ConstraintLayout_placeholder_content;
        public static final int ConstraintLayout_placeholder_emptyVisibility;
        public static final int[] ConstraintSet;
        public static final int ConstraintSet_android_alpha;
        public static final int ConstraintSet_android_elevation;
        public static final int ConstraintSet_android_id;
        public static final int ConstraintSet_android_layout_height;
        public static final int ConstraintSet_android_layout_marginBottom;
        public static final int ConstraintSet_android_layout_marginEnd;
        public static final int ConstraintSet_android_layout_marginLeft;
        public static final int ConstraintSet_android_layout_marginRight;
        public static final int ConstraintSet_android_layout_marginStart;
        public static final int ConstraintSet_android_layout_marginTop;
        public static final int ConstraintSet_android_layout_width;
        public static final int ConstraintSet_android_maxHeight;
        public static final int ConstraintSet_android_maxWidth;
        public static final int ConstraintSet_android_minHeight;
        public static final int ConstraintSet_android_minWidth;
        public static final int ConstraintSet_android_orientation;
        public static final int ConstraintSet_android_rotation;
        public static final int ConstraintSet_android_rotationX;
        public static final int ConstraintSet_android_rotationY;
        public static final int ConstraintSet_android_scaleX;
        public static final int ConstraintSet_android_scaleY;
        public static final int ConstraintSet_android_transformPivotX;
        public static final int ConstraintSet_android_transformPivotY;
        public static final int ConstraintSet_android_translationX;
        public static final int ConstraintSet_android_translationY;
        public static final int ConstraintSet_android_translationZ;
        public static final int ConstraintSet_android_visibility;
        public static final int ConstraintSet_barrierAllowsGoneWidgets;
        public static final int ConstraintSet_barrierDirection;
        public static final int ConstraintSet_chainUseRtl;
        public static final int ConstraintSet_constraint_referenced_ids;
        public static final int ConstraintSet_layout_constrainedHeight;
        public static final int ConstraintSet_layout_constrainedWidth;
        public static final int ConstraintSet_layout_constraintBaseline_creator;
        public static final int ConstraintSet_layout_constraintBaseline_toBaselineOf;
        public static final int ConstraintSet_layout_constraintBottom_creator;
        public static final int ConstraintSet_layout_constraintBottom_toBottomOf;
        public static final int ConstraintSet_layout_constraintBottom_toTopOf;
        public static final int ConstraintSet_layout_constraintCircle;
        public static final int ConstraintSet_layout_constraintCircleAngle;
        public static final int ConstraintSet_layout_constraintCircleRadius;
        public static final int ConstraintSet_layout_constraintDimensionRatio;
        public static final int ConstraintSet_layout_constraintEnd_toEndOf;
        public static final int ConstraintSet_layout_constraintEnd_toStartOf;
        public static final int ConstraintSet_layout_constraintGuide_begin;
        public static final int ConstraintSet_layout_constraintGuide_end;
        public static final int ConstraintSet_layout_constraintGuide_percent;
        public static final int ConstraintSet_layout_constraintHeight_default;
        public static final int ConstraintSet_layout_constraintHeight_max;
        public static final int ConstraintSet_layout_constraintHeight_min;
        public static final int ConstraintSet_layout_constraintHeight_percent;
        public static final int ConstraintSet_layout_constraintHorizontal_bias;
        public static final int ConstraintSet_layout_constraintHorizontal_chainStyle;
        public static final int ConstraintSet_layout_constraintHorizontal_weight;
        public static final int ConstraintSet_layout_constraintLeft_creator;
        public static final int ConstraintSet_layout_constraintLeft_toLeftOf;
        public static final int ConstraintSet_layout_constraintLeft_toRightOf;
        public static final int ConstraintSet_layout_constraintRight_creator;
        public static final int ConstraintSet_layout_constraintRight_toLeftOf;
        public static final int ConstraintSet_layout_constraintRight_toRightOf;
        public static final int ConstraintSet_layout_constraintStart_toEndOf;
        public static final int ConstraintSet_layout_constraintStart_toStartOf;
        public static final int ConstraintSet_layout_constraintTop_creator;
        public static final int ConstraintSet_layout_constraintTop_toBottomOf;
        public static final int ConstraintSet_layout_constraintTop_toTopOf;
        public static final int ConstraintSet_layout_constraintVertical_bias;
        public static final int ConstraintSet_layout_constraintVertical_chainStyle;
        public static final int ConstraintSet_layout_constraintVertical_weight;
        public static final int ConstraintSet_layout_constraintWidth_default;
        public static final int ConstraintSet_layout_constraintWidth_max;
        public static final int ConstraintSet_layout_constraintWidth_min;
        public static final int ConstraintSet_layout_constraintWidth_percent;
        public static final int ConstraintSet_layout_editor_absoluteX;
        public static final int ConstraintSet_layout_editor_absoluteY;
        public static final int ConstraintSet_layout_goneMarginBottom;
        public static final int ConstraintSet_layout_goneMarginEnd;
        public static final int ConstraintSet_layout_goneMarginLeft;
        public static final int ConstraintSet_layout_goneMarginRight;
        public static final int ConstraintSet_layout_goneMarginStart;
        public static final int ConstraintSet_layout_goneMarginTop;
        public static final int[] LinearConstraintLayout;
        public static final int LinearConstraintLayout_android_orientation;

        public styleable() {
        }

        static {
            ConstraintLayout_Layout = StyleaUtils.getStyleableArryId("ConstraintLayout_Layout");
            ConstraintLayout_Layout_android_maxHeight = StyleaUtils.getStyleableId("ConstraintLayout_Layout_android_maxHeight");
            ConstraintLayout_Layout_android_maxWidth = StyleaUtils.getStyleableId("ConstraintLayout_Layout_android_maxWidth");
            ConstraintLayout_Layout_android_minHeight = StyleaUtils.getStyleableId("ConstraintLayout_Layout_android_minHeight");
            ConstraintLayout_Layout_android_minWidth = StyleaUtils.getStyleableId("ConstraintLayout_Layout_android_minWidth");
            ConstraintLayout_Layout_android_orientation = StyleaUtils.getStyleableId("ConstraintLayout_Layout_android_orientation");
            ConstraintLayout_Layout_barrierAllowsGoneWidgets = StyleaUtils.getStyleableId("ConstraintLayout_Layout_barrierAllowsGoneWidgets");
            ConstraintLayout_Layout_barrierDirection = StyleaUtils.getStyleableId("ConstraintLayout_Layout_barrierDirection");
            ConstraintLayout_Layout_chainUseRtl = StyleaUtils.getStyleableId("ConstraintLayout_Layout_chainUseRtl");
            ConstraintLayout_Layout_constraintSet = StyleaUtils.getStyleableId("ConstraintLayout_Layout_constraintSet");
            ConstraintLayout_Layout_constraint_referenced_ids = StyleaUtils.getStyleableId("ConstraintLayout_Layout_constraint_referenced_ids");
            ConstraintLayout_Layout_layout_constrainedHeight = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constrainedHeight");
            ConstraintLayout_Layout_layout_constrainedWidth = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constrainedWidth");
            ConstraintLayout_Layout_layout_constraintBaseline_creator = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintBaseline_creator");
            ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf");
            ConstraintLayout_Layout_layout_constraintBottom_creator = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintBottom_creator");
            ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintBottom_toBottomOf");
            ConstraintLayout_Layout_layout_constraintBottom_toTopOf = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintBottom_toTopOf");
            ConstraintLayout_Layout_layout_constraintCircle = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintCircle");
            ConstraintLayout_Layout_layout_constraintCircleAngle = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintCircleAngle");
            ConstraintLayout_Layout_layout_constraintCircleRadius = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintCircleRadius");
            ConstraintLayout_Layout_layout_constraintDimensionRatio = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintDimensionRatio");
            ConstraintLayout_Layout_layout_constraintEnd_toEndOf = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintEnd_toEndOf");
            ConstraintLayout_Layout_layout_constraintEnd_toStartOf = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintEnd_toStartOf");
            ConstraintLayout_Layout_layout_constraintGuide_begin = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintGuide_begin");
            ConstraintLayout_Layout_layout_constraintGuide_end = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintGuide_end");
            ConstraintLayout_Layout_layout_constraintGuide_percent = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintGuide_percent");
            ConstraintLayout_Layout_layout_constraintHeight_default = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintHeight_default");
            ConstraintLayout_Layout_layout_constraintHeight_max = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintHeight_max");
            ConstraintLayout_Layout_layout_constraintHeight_min = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintHeight_min");
            ConstraintLayout_Layout_layout_constraintHeight_percent = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintHeight_percent");
            ConstraintLayout_Layout_layout_constraintHorizontal_bias = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintHorizontal_bias");
            ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle");
            ConstraintLayout_Layout_layout_constraintHorizontal_weight = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintHorizontal_weight");
            ConstraintLayout_Layout_layout_constraintLeft_creator = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintLeft_creator");
            ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintLeft_toLeftOf");
            ConstraintLayout_Layout_layout_constraintLeft_toRightOf = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintLeft_toRightOf");
            ConstraintLayout_Layout_layout_constraintRight_creator = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintRight_creator");
            ConstraintLayout_Layout_layout_constraintRight_toLeftOf = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintRight_toLeftOf");
            ConstraintLayout_Layout_layout_constraintRight_toRightOf = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintRight_toRightOf");
            ConstraintLayout_Layout_layout_constraintStart_toEndOf = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintStart_toEndOf");
            ConstraintLayout_Layout_layout_constraintStart_toStartOf = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintStart_toStartOf");
            ConstraintLayout_Layout_layout_constraintTop_creator = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintTop_creator");
            ConstraintLayout_Layout_layout_constraintTop_toBottomOf = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintTop_toBottomOf");
            ConstraintLayout_Layout_layout_constraintTop_toTopOf = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintTop_toTopOf");
            ConstraintLayout_Layout_layout_constraintVertical_bias = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintVertical_bias");
            ConstraintLayout_Layout_layout_constraintVertical_chainStyle = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintVertical_chainStyle");
            ConstraintLayout_Layout_layout_constraintVertical_weight = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintVertical_weight");
            ConstraintLayout_Layout_layout_constraintWidth_default = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintWidth_default");
            ConstraintLayout_Layout_layout_constraintWidth_max = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintWidth_max");
            ConstraintLayout_Layout_layout_constraintWidth_min = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintWidth_min");
            ConstraintLayout_Layout_layout_constraintWidth_percent = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_constraintWidth_percent");
            ConstraintLayout_Layout_layout_editor_absoluteX = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_editor_absoluteX");
            ConstraintLayout_Layout_layout_editor_absoluteY = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_editor_absoluteY");
            ConstraintLayout_Layout_layout_goneMarginBottom = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_goneMarginBottom");
            ConstraintLayout_Layout_layout_goneMarginEnd = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_goneMarginEnd");
            ConstraintLayout_Layout_layout_goneMarginLeft = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_goneMarginLeft");
            ConstraintLayout_Layout_layout_goneMarginRight = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_goneMarginRight");
            ConstraintLayout_Layout_layout_goneMarginStart = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_goneMarginStart");
            ConstraintLayout_Layout_layout_goneMarginTop = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_goneMarginTop");
            ConstraintLayout_Layout_layout_optimizationLevel = StyleaUtils.getStyleableId("ConstraintLayout_Layout_layout_optimizationLevel");
            ConstraintLayout_placeholder = StyleaUtils.getStyleableArryId("ConstraintLayout_placeholder");
            ConstraintLayout_placeholder_content = StyleaUtils.getStyleableId("ConstraintLayout_placeholder_content");
            ConstraintLayout_placeholder_emptyVisibility = StyleaUtils.getStyleableId("ConstraintLayout_placeholder_emptyVisibility");
            ConstraintSet = StyleaUtils.getStyleableArryId("ConstraintSet");
            ConstraintSet_android_alpha = StyleaUtils.getStyleableId("ConstraintSet_android_alpha");
            ConstraintSet_android_elevation = StyleaUtils.getStyleableId("ConstraintSet_android_elevation");
            ConstraintSet_android_id = StyleaUtils.getStyleableId("ConstraintSet_android_id");
            ConstraintSet_android_layout_height = StyleaUtils.getStyleableId("ConstraintSet_android_layout_height");
            ConstraintSet_android_layout_marginBottom = StyleaUtils.getStyleableId("ConstraintSet_android_layout_marginBottom");
            ConstraintSet_android_layout_marginEnd = StyleaUtils.getStyleableId("ConstraintSet_android_layout_marginEnd");
            ConstraintSet_android_layout_marginLeft = StyleaUtils.getStyleableId("ConstraintSet_android_layout_marginLeft");
            ConstraintSet_android_layout_marginRight = StyleaUtils.getStyleableId("ConstraintSet_android_layout_marginRight");
            ConstraintSet_android_layout_marginStart = StyleaUtils.getStyleableId("ConstraintSet_android_layout_marginStart");
            ConstraintSet_android_layout_marginTop = StyleaUtils.getStyleableId("ConstraintSet_android_layout_marginTop");
            ConstraintSet_android_layout_width = StyleaUtils.getStyleableId("ConstraintSet_android_layout_width");
            ConstraintSet_android_maxHeight = StyleaUtils.getStyleableId("ConstraintSet_android_maxHeight");
            ConstraintSet_android_maxWidth = StyleaUtils.getStyleableId("ConstraintSet_android_maxWidth");
            ConstraintSet_android_minHeight = StyleaUtils.getStyleableId("ConstraintSet_android_minHeight");
            ConstraintSet_android_minWidth = StyleaUtils.getStyleableId("ConstraintSet_android_minWidth");
            ConstraintSet_android_orientation = StyleaUtils.getStyleableId("ConstraintSet_android_orientation");
            ConstraintSet_android_rotation = StyleaUtils.getStyleableId("ConstraintSet_android_rotation");
            ConstraintSet_android_rotationX = StyleaUtils.getStyleableId("ConstraintSet_android_rotationX");
            ConstraintSet_android_rotationY = StyleaUtils.getStyleableId("ConstraintSet_android_rotationY");
            ConstraintSet_android_scaleX = StyleaUtils.getStyleableId("ConstraintSet_android_scaleX");
            ConstraintSet_android_scaleY = StyleaUtils.getStyleableId("ConstraintSet_android_scaleY");
            ConstraintSet_android_transformPivotX = StyleaUtils.getStyleableId("ConstraintSet_android_transformPivotX");
            ConstraintSet_android_transformPivotY = StyleaUtils.getStyleableId("ConstraintSet_android_transformPivotY");
            ConstraintSet_android_translationX = StyleaUtils.getStyleableId("ConstraintSet_android_translationX");
            ConstraintSet_android_translationY = StyleaUtils.getStyleableId("ConstraintSet_android_translationY");
            ConstraintSet_android_translationZ = StyleaUtils.getStyleableId("ConstraintSet_android_translationZ");
            ConstraintSet_android_visibility = StyleaUtils.getStyleableId("ConstraintSet_android_visibility");
            ConstraintSet_barrierAllowsGoneWidgets = StyleaUtils.getStyleableId("ConstraintSet_barrierAllowsGoneWidgets");
            ConstraintSet_barrierDirection = StyleaUtils.getStyleableId("ConstraintSet_barrierDirection");
            ConstraintSet_chainUseRtl = StyleaUtils.getStyleableId("ConstraintSet_chainUseRtl");
            ConstraintSet_constraint_referenced_ids = StyleaUtils.getStyleableId("ConstraintSet_constraint_referenced_ids");
            ConstraintSet_layout_constrainedHeight = StyleaUtils.getStyleableId("ConstraintSet_layout_constrainedHeight");
            ConstraintSet_layout_constrainedWidth = StyleaUtils.getStyleableId("ConstraintSet_layout_constrainedWidth");
            ConstraintSet_layout_constraintBaseline_creator = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintBaseline_creator");
            ConstraintSet_layout_constraintBaseline_toBaselineOf = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintBaseline_toBaselineOf");
            ConstraintSet_layout_constraintBottom_creator = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintBottom_creator");
            ConstraintSet_layout_constraintBottom_toBottomOf = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintBottom_toBottomOf");
            ConstraintSet_layout_constraintBottom_toTopOf = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintBottom_toTopOf");
            ConstraintSet_layout_constraintCircle = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintCircle");
            ConstraintSet_layout_constraintCircleAngle = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintCircleAngle");
            ConstraintSet_layout_constraintCircleRadius = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintCircleRadius");
            ConstraintSet_layout_constraintDimensionRatio = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintDimensionRatio");
            ConstraintSet_layout_constraintEnd_toEndOf = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintEnd_toEndOf");
            ConstraintSet_layout_constraintEnd_toStartOf = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintEnd_toStartOf");
            ConstraintSet_layout_constraintGuide_begin = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintGuide_begin");
            ConstraintSet_layout_constraintGuide_end = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintGuide_end");
            ConstraintSet_layout_constraintGuide_percent = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintGuide_percent");
            ConstraintSet_layout_constraintHeight_default = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintHeight_default");
            ConstraintSet_layout_constraintHeight_max = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintHeight_max");
            ConstraintSet_layout_constraintHeight_min = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintHeight_min");
            ConstraintSet_layout_constraintHeight_percent = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintHeight_percent");
            ConstraintSet_layout_constraintHorizontal_bias = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintHorizontal_bias");
            ConstraintSet_layout_constraintHorizontal_chainStyle = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintHorizontal_chainStyle");
            ConstraintSet_layout_constraintHorizontal_weight = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintHorizontal_weight");
            ConstraintSet_layout_constraintLeft_creator = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintLeft_creator");
            ConstraintSet_layout_constraintLeft_toLeftOf = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintLeft_toLeftOf");
            ConstraintSet_layout_constraintLeft_toRightOf = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintLeft_toRightOf");
            ConstraintSet_layout_constraintRight_creator = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintRight_creator");
            ConstraintSet_layout_constraintRight_toLeftOf = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintRight_toLeftOf");
            ConstraintSet_layout_constraintRight_toRightOf = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintRight_toRightOf");
            ConstraintSet_layout_constraintStart_toEndOf = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintStart_toEndOf");
            ConstraintSet_layout_constraintStart_toStartOf = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintStart_toStartOf");
            ConstraintSet_layout_constraintTop_creator = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintTop_creator");
            ConstraintSet_layout_constraintTop_toBottomOf = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintTop_toBottomOf");
            ConstraintSet_layout_constraintTop_toTopOf = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintTop_toTopOf");
            ConstraintSet_layout_constraintVertical_bias = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintVertical_bias");
            ConstraintSet_layout_constraintVertical_chainStyle = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintVertical_chainStyle");
            ConstraintSet_layout_constraintVertical_weight = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintVertical_weight");
            ConstraintSet_layout_constraintWidth_default = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintWidth_default");
            ConstraintSet_layout_constraintWidth_max = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintWidth_max");
            ConstraintSet_layout_constraintWidth_min = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintWidth_min");
            ConstraintSet_layout_constraintWidth_percent = StyleaUtils.getStyleableId("ConstraintSet_layout_constraintWidth_percent");
            ConstraintSet_layout_editor_absoluteX = StyleaUtils.getStyleableId("ConstraintSet_layout_editor_absoluteX");
            ConstraintSet_layout_editor_absoluteY = StyleaUtils.getStyleableId("ConstraintSet_layout_editor_absoluteY");
            ConstraintSet_layout_goneMarginBottom = StyleaUtils.getStyleableId("ConstraintSet_layout_goneMarginBottom");
            ConstraintSet_layout_goneMarginEnd = StyleaUtils.getStyleableId("ConstraintSet_layout_goneMarginEnd");
            ConstraintSet_layout_goneMarginLeft = StyleaUtils.getStyleableId("ConstraintSet_layout_goneMarginLeft");
            ConstraintSet_layout_goneMarginRight = StyleaUtils.getStyleableId("ConstraintSet_layout_goneMarginRight");
            ConstraintSet_layout_goneMarginStart = StyleaUtils.getStyleableId("ConstraintSet_layout_goneMarginStart");
            ConstraintSet_layout_goneMarginTop = StyleaUtils.getStyleableId("ConstraintSet_layout_goneMarginTop");
            LinearConstraintLayout = StyleaUtils.getStyleableArryId("LinearConstraintLayout");
            LinearConstraintLayout_android_orientation = StyleaUtils.getStyleableId("LinearConstraintLayout_android_orientation");
        }
    }

    public static final class id {
        public static final int bottom;
        public static final int end;
        public static final int gone;
        public static final int invisible;
        public static final int left;
        public static final int packed;
        public static final int parent;
        public static final int percent;
        public static final int right;
        public static final int spread;
        public static final int spread_inside;
        public static final int start;
        public static final int top;
        public static final int wrap;

        public id() {
        }

        static {
            bottom = ResourcesUtil.getId("bottom");
            end = ResourcesUtil.getId("end");
            gone = ResourcesUtil.getId("gone");
            invisible = ResourcesUtil.getId("invisible");
            left = ResourcesUtil.getId("left");
            packed = ResourcesUtil.getId("packed");
            parent = ResourcesUtil.getId("parent");
            percent = ResourcesUtil.getId("percent");
            right = ResourcesUtil.getId("right");
            spread = ResourcesUtil.getId("spread");
            spread_inside = ResourcesUtil.getId("spread_inside");
            start = ResourcesUtil.getId("start");
            top = ResourcesUtil.getId("top");
            wrap = ResourcesUtil.getId("wrap");
        }
    }

    public static final class attr {
        public static final int barrierAllowsGoneWidgets;
        public static final int barrierDirection;
        public static final int chainUseRtl;
        public static final int constraintSet;
        public static final int constraint_referenced_ids;
        public static final int content;
        public static final int emptyVisibility;
        public static final int layout_constrainedHeight;
        public static final int layout_constrainedWidth;
        public static final int layout_constraintBaseline_creator;
        public static final int layout_constraintBaseline_toBaselineOf;
        public static final int layout_constraintBottom_creator;
        public static final int layout_constraintBottom_toBottomOf;
        public static final int layout_constraintBottom_toTopOf;
        public static final int layout_constraintCircle;
        public static final int layout_constraintCircleAngle;
        public static final int layout_constraintCircleRadius;
        public static final int layout_constraintDimensionRatio;
        public static final int layout_constraintEnd_toEndOf;
        public static final int layout_constraintEnd_toStartOf;
        public static final int layout_constraintGuide_begin;
        public static final int layout_constraintGuide_end;
        public static final int layout_constraintGuide_percent;
        public static final int layout_constraintHeight_default;
        public static final int layout_constraintHeight_max;
        public static final int layout_constraintHeight_min;
        public static final int layout_constraintHeight_percent;
        public static final int layout_constraintHorizontal_bias;
        public static final int layout_constraintHorizontal_chainStyle;
        public static final int layout_constraintHorizontal_weight;
        public static final int layout_constraintLeft_creator;
        public static final int layout_constraintLeft_toLeftOf;
        public static final int layout_constraintLeft_toRightOf;
        public static final int layout_constraintRight_creator;
        public static final int layout_constraintRight_toLeftOf;
        public static final int layout_constraintRight_toRightOf;
        public static final int layout_constraintStart_toEndOf;
        public static final int layout_constraintStart_toStartOf;
        public static final int layout_constraintTop_creator;
        public static final int layout_constraintTop_toBottomOf;
        public static final int layout_constraintTop_toTopOf;
        public static final int layout_constraintVertical_bias;
        public static final int layout_constraintVertical_chainStyle;
        public static final int layout_constraintVertical_weight;
        public static final int layout_constraintWidth_default;
        public static final int layout_constraintWidth_max;
        public static final int layout_constraintWidth_min;
        public static final int layout_constraintWidth_percent;
        public static final int layout_editor_absoluteX;
        public static final int layout_editor_absoluteY;
        public static final int layout_goneMarginBottom;
        public static final int layout_goneMarginEnd;
        public static final int layout_goneMarginLeft;
        public static final int layout_goneMarginRight;
        public static final int layout_goneMarginStart;
        public static final int layout_goneMarginTop;
        public static final int layout_optimizationLevel;

        public attr() {
        }

        static {
            barrierAllowsGoneWidgets = ResourcesUtil.getAttr("barrierAllowsGoneWidgets");
            barrierDirection = ResourcesUtil.getAttr("barrierDirection");
            chainUseRtl = ResourcesUtil.getAttr("chainUseRtl");
            constraintSet = ResourcesUtil.getAttr("constraintSet");
            constraint_referenced_ids = ResourcesUtil.getAttr("constraint_referenced_ids");
            content = ResourcesUtil.getAttr("content");
            emptyVisibility = ResourcesUtil.getAttr("emptyVisibility");
            layout_constrainedHeight = ResourcesUtil.getAttr("layout_constrainedHeight");
            layout_constrainedWidth = ResourcesUtil.getAttr("layout_constrainedWidth");
            layout_constraintBaseline_creator = ResourcesUtil.getAttr("layout_constraintBaseline_creator");
            layout_constraintBaseline_toBaselineOf = ResourcesUtil.getAttr("layout_constraintBaseline_toBaselineOf");
            layout_constraintBottom_creator = ResourcesUtil.getAttr("layout_constraintBottom_creator");
            layout_constraintBottom_toBottomOf = ResourcesUtil.getAttr("layout_constraintBottom_toBottomOf");
            layout_constraintBottom_toTopOf = ResourcesUtil.getAttr("layout_constraintBottom_toTopOf");
            layout_constraintCircle = ResourcesUtil.getAttr("layout_constraintCircle");
            layout_constraintCircleAngle = ResourcesUtil.getAttr("layout_constraintCircleAngle");
            layout_constraintCircleRadius = ResourcesUtil.getAttr("layout_constraintCircleRadius");
            layout_constraintDimensionRatio = ResourcesUtil.getAttr("layout_constraintDimensionRatio");
            layout_constraintEnd_toEndOf = ResourcesUtil.getAttr("layout_constraintEnd_toEndOf");
            layout_constraintEnd_toStartOf = ResourcesUtil.getAttr("layout_constraintEnd_toStartOf");
            layout_constraintGuide_begin = ResourcesUtil.getAttr("layout_constraintGuide_begin");
            layout_constraintGuide_end = ResourcesUtil.getAttr("layout_constraintGuide_end");
            layout_constraintGuide_percent = ResourcesUtil.getAttr("layout_constraintGuide_percent");
            layout_constraintHeight_default = ResourcesUtil.getAttr("layout_constraintHeight_default");
            layout_constraintHeight_max = ResourcesUtil.getAttr("layout_constraintHeight_max");
            layout_constraintHeight_min = ResourcesUtil.getAttr("layout_constraintHeight_min");
            layout_constraintHeight_percent = ResourcesUtil.getAttr("layout_constraintHeight_percent");
            layout_constraintHorizontal_bias = ResourcesUtil.getAttr("layout_constraintHorizontal_bias");
            layout_constraintHorizontal_chainStyle = ResourcesUtil.getAttr("layout_constraintHorizontal_chainStyle");
            layout_constraintHorizontal_weight = ResourcesUtil.getAttr("layout_constraintHorizontal_weight");
            layout_constraintLeft_creator = ResourcesUtil.getAttr("layout_constraintLeft_creator");
            layout_constraintLeft_toLeftOf = ResourcesUtil.getAttr("layout_constraintLeft_toLeftOf");
            layout_constraintLeft_toRightOf = ResourcesUtil.getAttr("layout_constraintLeft_toRightOf");
            layout_constraintRight_creator = ResourcesUtil.getAttr("layout_constraintRight_creator");
            layout_constraintRight_toLeftOf = ResourcesUtil.getAttr("layout_constraintRight_toLeftOf");
            layout_constraintRight_toRightOf = ResourcesUtil.getAttr("layout_constraintRight_toRightOf");
            layout_constraintStart_toEndOf = ResourcesUtil.getAttr("layout_constraintStart_toEndOf");
            layout_constraintStart_toStartOf = ResourcesUtil.getAttr("layout_constraintStart_toStartOf");
            layout_constraintTop_creator = ResourcesUtil.getAttr("layout_constraintTop_creator");
            layout_constraintTop_toBottomOf = ResourcesUtil.getAttr("layout_constraintTop_toBottomOf");
            layout_constraintTop_toTopOf = ResourcesUtil.getAttr("layout_constraintTop_toTopOf");
            layout_constraintVertical_bias = ResourcesUtil.getAttr("layout_constraintVertical_bias");
            layout_constraintVertical_chainStyle = ResourcesUtil.getAttr("layout_constraintVertical_chainStyle");
            layout_constraintVertical_weight = ResourcesUtil.getAttr("layout_constraintVertical_weight");
            layout_constraintWidth_default = ResourcesUtil.getAttr("layout_constraintWidth_default");
            layout_constraintWidth_max = ResourcesUtil.getAttr("layout_constraintWidth_max");
            layout_constraintWidth_min = ResourcesUtil.getAttr("layout_constraintWidth_min");
            layout_constraintWidth_percent = ResourcesUtil.getAttr("layout_constraintWidth_percent");
            layout_editor_absoluteX = ResourcesUtil.getAttr("layout_editor_absoluteX");
            layout_editor_absoluteY = ResourcesUtil.getAttr("layout_editor_absoluteY");
            layout_goneMarginBottom = ResourcesUtil.getAttr("layout_goneMarginBottom");
            layout_goneMarginEnd = ResourcesUtil.getAttr("layout_goneMarginEnd");
            layout_goneMarginLeft = ResourcesUtil.getAttr("layout_goneMarginLeft");
            layout_goneMarginRight = ResourcesUtil.getAttr("layout_goneMarginRight");
            layout_goneMarginStart = ResourcesUtil.getAttr("layout_goneMarginStart");
            layout_goneMarginTop = ResourcesUtil.getAttr("layout_goneMarginTop");
            layout_optimizationLevel = ResourcesUtil.getAttr("layout_optimizationLevel");
        }
    }
}