//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package android.support.constraint;

public final class R {
    public R() {
    }

    public static final class styleable {
        public static final int[] ConstraintLayout_Layout;
        public static final int ConstraintLayout_Layout_android_maxHeight;
        public static final int ConstraintLayout_Layout_android_maxWidth;
        public static final int ConstraintLayout_Layout_android_minHeight;
        public static final int ConstraintLayout_Layout_android_minWidth;
        public static final int ConstraintLayout_Layout_android_orientation;
        public static final int ConstraintLayout_Layout_barrierAllowsGoneWidgets;
        public static final int ConstraintLayout_Layout_barrierDirection;
        public static final int ConstraintLayout_Layout_chainUseRtl;
        public static final int ConstraintLayout_Layout_constraintSet;
        public static final int ConstraintLayout_Layout_constraint_referenced_ids;
        public static final int ConstraintLayout_Layout_layout_constrainedHeight;
        public static final int ConstraintLayout_Layout_layout_constrainedWidth;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_creator;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_creator;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toTopOf;
        public static final int ConstraintLayout_Layout_layout_constraintCircle;
        public static final int ConstraintLayout_Layout_layout_constraintCircleAngle;
        public static final int ConstraintLayout_Layout_layout_constraintCircleRadius;
        public static final int ConstraintLayout_Layout_layout_constraintDimensionRatio;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toEndOf;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toStartOf;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_begin;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_end;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_percent;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_default;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_max;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_min;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_percent;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_bias;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_weight;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_creator;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toRightOf;
        public static final int ConstraintLayout_Layout_layout_constraintRight_creator;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toLeftOf;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toRightOf;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toEndOf;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toStartOf;
        public static final int ConstraintLayout_Layout_layout_constraintTop_creator;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toBottomOf;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toTopOf;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_bias;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_chainStyle;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_weight;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_default;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_max;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_min;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_percent;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteX;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteY;
        public static final int ConstraintLayout_Layout_layout_goneMarginBottom;
        public static final int ConstraintLayout_Layout_layout_goneMarginEnd;
        public static final int ConstraintLayout_Layout_layout_goneMarginLeft;
        public static final int ConstraintLayout_Layout_layout_goneMarginRight;
        public static final int ConstraintLayout_Layout_layout_goneMarginStart;
        public static final int ConstraintLayout_Layout_layout_goneMarginTop;
        public static final int ConstraintLayout_Layout_layout_optimizationLevel;
        public static final int[] ConstraintLayout_placeholder;
        public static final int ConstraintLayout_placeholder_content;
        public static final int ConstraintLayout_placeholder_emptyVisibility;
        public static final int[] ConstraintSet;
        public static final int ConstraintSet_android_alpha;
        public static final int ConstraintSet_android_elevation;
        public static final int ConstraintSet_android_id;
        public static final int ConstraintSet_android_layout_height;
        public static final int ConstraintSet_android_layout_marginBottom;
        public static final int ConstraintSet_android_layout_marginEnd;
        public static final int ConstraintSet_android_layout_marginLeft;
        public static final int ConstraintSet_android_layout_marginRight;
        public static final int ConstraintSet_android_layout_marginStart;
        public static final int ConstraintSet_android_layout_marginTop;
        public static final int ConstraintSet_android_layout_width;
        public static final int ConstraintSet_android_maxHeight;
        public static final int ConstraintSet_android_maxWidth;
        public static final int ConstraintSet_android_minHeight;
        public static final int ConstraintSet_android_minWidth;
        public static final int ConstraintSet_android_orientation;
        public static final int ConstraintSet_android_rotation;
        public static final int ConstraintSet_android_rotationX;
        public static final int ConstraintSet_android_rotationY;
        public static final int ConstraintSet_android_scaleX;
        public static final int ConstraintSet_android_scaleY;
        public static final int ConstraintSet_android_transformPivotX;
        public static final int ConstraintSet_android_transformPivotY;
        public static final int ConstraintSet_android_translationX;
        public static final int ConstraintSet_android_translationY;
        public static final int ConstraintSet_android_translationZ;
        public static final int ConstraintSet_android_visibility;
        public static final int ConstraintSet_barrierAllowsGoneWidgets;
        public static final int ConstraintSet_barrierDirection;
        public static final int ConstraintSet_chainUseRtl;
        public static final int ConstraintSet_constraint_referenced_ids;
        public static final int ConstraintSet_layout_constrainedHeight;
        public static final int ConstraintSet_layout_constrainedWidth;
        public static final int ConstraintSet_layout_constraintBaseline_creator;
        public static final int ConstraintSet_layout_constraintBaseline_toBaselineOf;
        public static final int ConstraintSet_layout_constraintBottom_creator;
        public static final int ConstraintSet_layout_constraintBottom_toBottomOf;
        public static final int ConstraintSet_layout_constraintBottom_toTopOf;
        public static final int ConstraintSet_layout_constraintCircle;
        public static final int ConstraintSet_layout_constraintCircleAngle;
        public static final int ConstraintSet_layout_constraintCircleRadius;
        public static final int ConstraintSet_layout_constraintDimensionRatio;
        public static final int ConstraintSet_layout_constraintEnd_toEndOf;
        public static final int ConstraintSet_layout_constraintEnd_toStartOf;
        public static final int ConstraintSet_layout_constraintGuide_begin;
        public static final int ConstraintSet_layout_constraintGuide_end;
        public static final int ConstraintSet_layout_constraintGuide_percent;
        public static final int ConstraintSet_layout_constraintHeight_default;
        public static final int ConstraintSet_layout_constraintHeight_max;
        public static final int ConstraintSet_layout_constraintHeight_min;
        public static final int ConstraintSet_layout_constraintHeight_percent;
        public static final int ConstraintSet_layout_constraintHorizontal_bias;
        public static final int ConstraintSet_layout_constraintHorizontal_chainStyle;
        public static final int ConstraintSet_layout_constraintHorizontal_weight;
        public static final int ConstraintSet_layout_constraintLeft_creator;
        public static final int ConstraintSet_layout_constraintLeft_toLeftOf;
        public static final int ConstraintSet_layout_constraintLeft_toRightOf;
        public static final int ConstraintSet_layout_constraintRight_creator;
        public static final int ConstraintSet_layout_constraintRight_toLeftOf;
        public static final int ConstraintSet_layout_constraintRight_toRightOf;
        public static final int ConstraintSet_layout_constraintStart_toEndOf;
        public static final int ConstraintSet_layout_constraintStart_toStartOf;
        public static final int ConstraintSet_layout_constraintTop_creator;
        public static final int ConstraintSet_layout_constraintTop_toBottomOf;
        public static final int ConstraintSet_layout_constraintTop_toTopOf;
        public static final int ConstraintSet_layout_constraintVertical_bias;
        public static final int ConstraintSet_layout_constraintVertical_chainStyle;
        public static final int ConstraintSet_layout_constraintVertical_weight;
        public static final int ConstraintSet_layout_constraintWidth_default;
        public static final int ConstraintSet_layout_constraintWidth_max;
        public static final int ConstraintSet_layout_constraintWidth_min;
        public static final int ConstraintSet_layout_constraintWidth_percent;
        public static final int ConstraintSet_layout_editor_absoluteX;
        public static final int ConstraintSet_layout_editor_absoluteY;
        public static final int ConstraintSet_layout_goneMarginBottom;
        public static final int ConstraintSet_layout_goneMarginEnd;
        public static final int ConstraintSet_layout_goneMarginLeft;
        public static final int ConstraintSet_layout_goneMarginRight;
        public static final int ConstraintSet_layout_goneMarginStart;
        public static final int ConstraintSet_layout_goneMarginTop;
        public static final int[] LinearConstraintLayout;
        public static final int LinearConstraintLayout_android_orientation;

        public styleable() {
        }

        static {
            ConstraintLayout_Layout = R.styleable.ConstraintLayout_Layout;
            ConstraintLayout_Layout_android_maxHeight = R.styleable.ConstraintLayout_Layout_android_maxHeight;
            ConstraintLayout_Layout_android_maxWidth = R.styleable.ConstraintLayout_Layout_android_maxWidth;
            ConstraintLayout_Layout_android_minHeight = R.styleable.ConstraintLayout_Layout_android_minHeight;
            ConstraintLayout_Layout_android_minWidth = R.styleable.ConstraintLayout_Layout_android_minWidth;
            ConstraintLayout_Layout_android_orientation = R.styleable.ConstraintLayout_Layout_android_orientation;
            ConstraintLayout_Layout_barrierAllowsGoneWidgets = R.styleable.ConstraintLayout_Layout_barrierAllowsGoneWidgets;
            ConstraintLayout_Layout_barrierDirection = R.styleable.ConstraintLayout_Layout_barrierDirection;
            ConstraintLayout_Layout_chainUseRtl = R.styleable.ConstraintLayout_Layout_chainUseRtl;
            ConstraintLayout_Layout_constraintSet = R.styleable.ConstraintLayout_Layout_constraintSet;
            ConstraintLayout_Layout_constraint_referenced_ids = R.styleable.ConstraintLayout_Layout_constraint_referenced_ids;
            ConstraintLayout_Layout_layout_constrainedHeight = R.styleable.ConstraintLayout_Layout_layout_constrainedHeight;
            ConstraintLayout_Layout_layout_constrainedWidth = R.styleable.ConstraintLayout_Layout_layout_constrainedWidth;
            ConstraintLayout_Layout_layout_constraintBaseline_creator = R.styleable.ConstraintLayout_Layout_layout_constraintBaseline_creator;
            ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = R.styleable.ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf;
            ConstraintLayout_Layout_layout_constraintBottom_creator = R.styleable.ConstraintLayout_Layout_layout_constraintBottom_creator;
            ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = R.styleable.ConstraintLayout_Layout_layout_constraintBottom_toBottomOf;
            ConstraintLayout_Layout_layout_constraintBottom_toTopOf = R.styleable.ConstraintLayout_Layout_layout_constraintBottom_toTopOf;
            ConstraintLayout_Layout_layout_constraintCircle = R.styleable.ConstraintLayout_Layout_layout_constraintCircle;
            ConstraintLayout_Layout_layout_constraintCircleAngle = R.styleable.ConstraintLayout_Layout_layout_constraintCircleAngle;
            ConstraintLayout_Layout_layout_constraintCircleRadius = R.styleable.ConstraintLayout_Layout_layout_constraintCircleRadius;
            ConstraintLayout_Layout_layout_constraintDimensionRatio = R.styleable.ConstraintLayout_Layout_layout_constraintDimensionRatio;
            ConstraintLayout_Layout_layout_constraintEnd_toEndOf = R.styleable.ConstraintLayout_Layout_layout_constraintEnd_toEndOf;
            ConstraintLayout_Layout_layout_constraintEnd_toStartOf = R.styleable.ConstraintLayout_Layout_layout_constraintEnd_toStartOf;
            ConstraintLayout_Layout_layout_constraintGuide_begin = R.styleable.ConstraintLayout_Layout_layout_constraintGuide_begin;
            ConstraintLayout_Layout_layout_constraintGuide_end = R.styleable.ConstraintLayout_Layout_layout_constraintGuide_end;
            ConstraintLayout_Layout_layout_constraintGuide_percent = R.styleable.ConstraintLayout_Layout_layout_constraintGuide_percent;
            ConstraintLayout_Layout_layout_constraintHeight_default = R.styleable.ConstraintLayout_Layout_layout_constraintHeight_default;
            ConstraintLayout_Layout_layout_constraintHeight_max = R.styleable.ConstraintLayout_Layout_layout_constraintHeight_max;
            ConstraintLayout_Layout_layout_constraintHeight_min = R.styleable.ConstraintLayout_Layout_layout_constraintHeight_min;
            ConstraintLayout_Layout_layout_constraintHeight_percent = R.styleable.ConstraintLayout_Layout_layout_constraintHeight_percent;
            ConstraintLayout_Layout_layout_constraintHorizontal_bias = R.styleable.ConstraintLayout_Layout_layout_constraintHorizontal_bias;
            ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = R.styleable.ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle;
            ConstraintLayout_Layout_layout_constraintHorizontal_weight = R.styleable.ConstraintLayout_Layout_layout_constraintHorizontal_weight;
            ConstraintLayout_Layout_layout_constraintLeft_creator = R.styleable.ConstraintLayout_Layout_layout_constraintLeft_creator;
            ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = R.styleable.ConstraintLayout_Layout_layout_constraintLeft_toLeftOf;
            ConstraintLayout_Layout_layout_constraintLeft_toRightOf = R.styleable.ConstraintLayout_Layout_layout_constraintLeft_toRightOf;
            ConstraintLayout_Layout_layout_constraintRight_creator = R.styleable.ConstraintLayout_Layout_layout_constraintRight_creator;
            ConstraintLayout_Layout_layout_constraintRight_toLeftOf = R.styleable.ConstraintLayout_Layout_layout_constraintRight_toLeftOf;
            ConstraintLayout_Layout_layout_constraintRight_toRightOf = R.styleable.ConstraintLayout_Layout_layout_constraintRight_toRightOf;
            ConstraintLayout_Layout_layout_constraintStart_toEndOf = R.styleable.ConstraintLayout_Layout_layout_constraintStart_toEndOf;
            ConstraintLayout_Layout_layout_constraintStart_toStartOf = R.styleable.ConstraintLayout_Layout_layout_constraintStart_toStartOf;
            ConstraintLayout_Layout_layout_constraintTop_creator = R.styleable.ConstraintLayout_Layout_layout_constraintTop_creator;
            ConstraintLayout_Layout_layout_constraintTop_toBottomOf = R.styleable.ConstraintLayout_Layout_layout_constraintTop_toBottomOf;
            ConstraintLayout_Layout_layout_constraintTop_toTopOf = R.styleable.ConstraintLayout_Layout_layout_constraintTop_toTopOf;
            ConstraintLayout_Layout_layout_constraintVertical_bias = R.styleable.ConstraintLayout_Layout_layout_constraintVertical_bias;
            ConstraintLayout_Layout_layout_constraintVertical_chainStyle = R.styleable.ConstraintLayout_Layout_layout_constraintVertical_chainStyle;
            ConstraintLayout_Layout_layout_constraintVertical_weight = R.styleable.ConstraintLayout_Layout_layout_constraintVertical_weight;
            ConstraintLayout_Layout_layout_constraintWidth_default = R.styleable.ConstraintLayout_Layout_layout_constraintWidth_default;
            ConstraintLayout_Layout_layout_constraintWidth_max = R.styleable.ConstraintLayout_Layout_layout_constraintWidth_max;
            ConstraintLayout_Layout_layout_constraintWidth_min = R.styleable.ConstraintLayout_Layout_layout_constraintWidth_min;
            ConstraintLayout_Layout_layout_constraintWidth_percent = R.styleable.ConstraintLayout_Layout_layout_constraintWidth_percent;
            ConstraintLayout_Layout_layout_editor_absoluteX = R.styleable.ConstraintLayout_Layout_layout_editor_absoluteX;
            ConstraintLayout_Layout_layout_editor_absoluteY = R.styleable.ConstraintLayout_Layout_layout_editor_absoluteY;
            ConstraintLayout_Layout_layout_goneMarginBottom = R.styleable.ConstraintLayout_Layout_layout_goneMarginBottom;
            ConstraintLayout_Layout_layout_goneMarginEnd = R.styleable.ConstraintLayout_Layout_layout_goneMarginEnd;
            ConstraintLayout_Layout_layout_goneMarginLeft = R.styleable.ConstraintLayout_Layout_layout_goneMarginLeft;
            ConstraintLayout_Layout_layout_goneMarginRight = R.styleable.ConstraintLayout_Layout_layout_goneMarginRight;
            ConstraintLayout_Layout_layout_goneMarginStart = R.styleable.ConstraintLayout_Layout_layout_goneMarginStart;
            ConstraintLayout_Layout_layout_goneMarginTop = R.styleable.ConstraintLayout_Layout_layout_goneMarginTop;
            ConstraintLayout_Layout_layout_optimizationLevel = R.styleable.ConstraintLayout_Layout_layout_optimizationLevel;
            ConstraintLayout_placeholder = R.styleable.ConstraintLayout_placeholder;
            ConstraintLayout_placeholder_content = R.styleable.ConstraintLayout_placeholder_content;
            ConstraintLayout_placeholder_emptyVisibility = R.styleable.ConstraintLayout_placeholder_emptyVisibility;
            ConstraintSet = R.styleable.ConstraintSet;
            ConstraintSet_android_alpha = R.styleable.ConstraintSet_android_alpha;
            ConstraintSet_android_elevation = R.styleable.ConstraintSet_android_elevation;
            ConstraintSet_android_id = R.styleable.ConstraintSet_android_id;
            ConstraintSet_android_layout_height = R.styleable.ConstraintSet_android_layout_height;
            ConstraintSet_android_layout_marginBottom = R.styleable.ConstraintSet_android_layout_marginBottom;
            ConstraintSet_android_layout_marginEnd = R.styleable.ConstraintSet_android_layout_marginEnd;
            ConstraintSet_android_layout_marginLeft = R.styleable.ConstraintSet_android_layout_marginLeft;
            ConstraintSet_android_layout_marginRight = R.styleable.ConstraintSet_android_layout_marginRight;
            ConstraintSet_android_layout_marginStart = R.styleable.ConstraintSet_android_layout_marginStart;
            ConstraintSet_android_layout_marginTop = R.styleable.ConstraintSet_android_layout_marginTop;
            ConstraintSet_android_layout_width = R.styleable.ConstraintSet_android_layout_width;
            ConstraintSet_android_maxHeight = R.styleable.ConstraintSet_android_maxHeight;
            ConstraintSet_android_maxWidth = R.styleable.ConstraintSet_android_maxWidth;
            ConstraintSet_android_minHeight = R.styleable.ConstraintSet_android_minHeight;
            ConstraintSet_android_minWidth = R.styleable.ConstraintSet_android_minWidth;
            ConstraintSet_android_orientation = R.styleable.ConstraintSet_android_orientation;
            ConstraintSet_android_rotation = R.styleable.ConstraintSet_android_rotation;
            ConstraintSet_android_rotationX = R.styleable.ConstraintSet_android_rotationX;
            ConstraintSet_android_rotationY = R.styleable.ConstraintSet_android_rotationY;
            ConstraintSet_android_scaleX = R.styleable.ConstraintSet_android_scaleX;
            ConstraintSet_android_scaleY = R.styleable.ConstraintSet_android_scaleY;
            ConstraintSet_android_transformPivotX = R.styleable.ConstraintSet_android_transformPivotX;
            ConstraintSet_android_transformPivotY = R.styleable.ConstraintSet_android_transformPivotY;
            ConstraintSet_android_translationX = R.styleable.ConstraintSet_android_translationX;
            ConstraintSet_android_translationY = R.styleable.ConstraintSet_android_translationY;
            ConstraintSet_android_translationZ = R.styleable.ConstraintSet_android_translationZ;
            ConstraintSet_android_visibility = R.styleable.ConstraintSet_android_visibility;
            ConstraintSet_barrierAllowsGoneWidgets = R.styleable.ConstraintSet_barrierAllowsGoneWidgets;
            ConstraintSet_barrierDirection = R.styleable.ConstraintSet_barrierDirection;
            ConstraintSet_chainUseRtl = R.styleable.ConstraintSet_chainUseRtl;
            ConstraintSet_constraint_referenced_ids = R.styleable.ConstraintSet_constraint_referenced_ids;
            ConstraintSet_layout_constrainedHeight = R.styleable.ConstraintSet_layout_constrainedHeight;
            ConstraintSet_layout_constrainedWidth = R.styleable.ConstraintSet_layout_constrainedWidth;
            ConstraintSet_layout_constraintBaseline_creator = R.styleable.ConstraintSet_layout_constraintBaseline_creator;
            ConstraintSet_layout_constraintBaseline_toBaselineOf = R.styleable.ConstraintSet_layout_constraintBaseline_toBaselineOf;
            ConstraintSet_layout_constraintBottom_creator = R.styleable.ConstraintSet_layout_constraintBottom_creator;
            ConstraintSet_layout_constraintBottom_toBottomOf = R.styleable.ConstraintSet_layout_constraintBottom_toBottomOf;
            ConstraintSet_layout_constraintBottom_toTopOf = R.styleable.ConstraintSet_layout_constraintBottom_toTopOf;
            ConstraintSet_layout_constraintCircle = R.styleable.ConstraintSet_layout_constraintCircle;
            ConstraintSet_layout_constraintCircleAngle = R.styleable.ConstraintSet_layout_constraintCircleAngle;
            ConstraintSet_layout_constraintCircleRadius = R.styleable.ConstraintSet_layout_constraintCircleRadius;
            ConstraintSet_layout_constraintDimensionRatio = R.styleable.ConstraintSet_layout_constraintDimensionRatio;
            ConstraintSet_layout_constraintEnd_toEndOf = R.styleable.ConstraintSet_layout_constraintEnd_toEndOf;
            ConstraintSet_layout_constraintEnd_toStartOf = R.styleable.ConstraintSet_layout_constraintEnd_toStartOf;
            ConstraintSet_layout_constraintGuide_begin = R.styleable.ConstraintSet_layout_constraintGuide_begin;
            ConstraintSet_layout_constraintGuide_end = R.styleable.ConstraintSet_layout_constraintGuide_end;
            ConstraintSet_layout_constraintGuide_percent = R.styleable.ConstraintSet_layout_constraintGuide_percent;
            ConstraintSet_layout_constraintHeight_default = R.styleable.ConstraintSet_layout_constraintHeight_default;
            ConstraintSet_layout_constraintHeight_max = R.styleable.ConstraintSet_layout_constraintHeight_max;
            ConstraintSet_layout_constraintHeight_min = R.styleable.ConstraintSet_layout_constraintHeight_min;
            ConstraintSet_layout_constraintHeight_percent = R.styleable.ConstraintSet_layout_constraintHeight_percent;
            ConstraintSet_layout_constraintHorizontal_bias = R.styleable.ConstraintSet_layout_constraintHorizontal_bias;
            ConstraintSet_layout_constraintHorizontal_chainStyle = R.styleable.ConstraintSet_layout_constraintHorizontal_chainStyle;
            ConstraintSet_layout_constraintHorizontal_weight = R.styleable.ConstraintSet_layout_constraintHorizontal_weight;
            ConstraintSet_layout_constraintLeft_creator = R.styleable.ConstraintSet_layout_constraintLeft_creator;
            ConstraintSet_layout_constraintLeft_toLeftOf = R.styleable.ConstraintSet_layout_constraintLeft_toLeftOf;
            ConstraintSet_layout_constraintLeft_toRightOf = R.styleable.ConstraintSet_layout_constraintLeft_toRightOf;
            ConstraintSet_layout_constraintRight_creator = R.styleable.ConstraintSet_layout_constraintRight_creator;
            ConstraintSet_layout_constraintRight_toLeftOf = R.styleable.ConstraintSet_layout_constraintRight_toLeftOf;
            ConstraintSet_layout_constraintRight_toRightOf = R.styleable.ConstraintSet_layout_constraintRight_toRightOf;
            ConstraintSet_layout_constraintStart_toEndOf = R.styleable.ConstraintSet_layout_constraintStart_toEndOf;
            ConstraintSet_layout_constraintStart_toStartOf = R.styleable.ConstraintSet_layout_constraintStart_toStartOf;
            ConstraintSet_layout_constraintTop_creator = R.styleable.ConstraintSet_layout_constraintTop_creator;
            ConstraintSet_layout_constraintTop_toBottomOf = R.styleable.ConstraintSet_layout_constraintTop_toBottomOf;
            ConstraintSet_layout_constraintTop_toTopOf = R.styleable.ConstraintSet_layout_constraintTop_toTopOf;
            ConstraintSet_layout_constraintVertical_bias = R.styleable.ConstraintSet_layout_constraintVertical_bias;
            ConstraintSet_layout_constraintVertical_chainStyle = R.styleable.ConstraintSet_layout_constraintVertical_chainStyle;
            ConstraintSet_layout_constraintVertical_weight = R.styleable.ConstraintSet_layout_constraintVertical_weight;
            ConstraintSet_layout_constraintWidth_default = R.styleable.ConstraintSet_layout_constraintWidth_default;
            ConstraintSet_layout_constraintWidth_max = R.styleable.ConstraintSet_layout_constraintWidth_max;
            ConstraintSet_layout_constraintWidth_min = R.styleable.ConstraintSet_layout_constraintWidth_min;
            ConstraintSet_layout_constraintWidth_percent = R.styleable.ConstraintSet_layout_constraintWidth_percent;
            ConstraintSet_layout_editor_absoluteX = R.styleable.ConstraintSet_layout_editor_absoluteX;
            ConstraintSet_layout_editor_absoluteY = R.styleable.ConstraintSet_layout_editor_absoluteY;
            ConstraintSet_layout_goneMarginBottom = R.styleable.ConstraintSet_layout_goneMarginBottom;
            ConstraintSet_layout_goneMarginEnd = R.styleable.ConstraintSet_layout_goneMarginEnd;
            ConstraintSet_layout_goneMarginLeft = R.styleable.ConstraintSet_layout_goneMarginLeft;
            ConstraintSet_layout_goneMarginRight = R.styleable.ConstraintSet_layout_goneMarginRight;
            ConstraintSet_layout_goneMarginStart = R.styleable.ConstraintSet_layout_goneMarginStart;
            ConstraintSet_layout_goneMarginTop = R.styleable.ConstraintSet_layout_goneMarginTop;
            LinearConstraintLayout = R.styleable.LinearConstraintLayout;
            LinearConstraintLayout_android_orientation = R.styleable.LinearConstraintLayout_android_orientation;
        }
    }

    public static final class id {
        public static final int bottom;
        public static final int end;
        public static final int gone;
        public static final int invisible;
        public static final int left;
        public static final int packed;
        public static final int parent;
        public static final int percent;
        public static final int right;
        public static final int spread;
        public static final int spread_inside;
        public static final int start;
        public static final int top;
        public static final int wrap;

        public id() {
        }

        static {
            bottom = R.id.bottom;
            end = R.id.end;
            gone = R.id.gone;
            invisible = R.id.invisible;
            left = R.id.left;
            packed = R.id.packed;
            parent = R.id.parent;
            percent = R.id.percent;
            right = R.id.right;
            spread = R.id.spread;
            spread_inside = R.id.spread_inside;
            start = R.id.start;
            top = R.id.top;
            wrap = R.id.wrap;
        }
    }

    public static final class attr {
        public static final int barrierAllowsGoneWidgets;
        public static final int barrierDirection;
        public static final int chainUseRtl;
        public static final int constraintSet;
        public static final int constraint_referenced_ids;
        public static final int content;
        public static final int emptyVisibility;
        public static final int layout_constrainedHeight;
        public static final int layout_constrainedWidth;
        public static final int layout_constraintBaseline_creator;
        public static final int layout_constraintBaseline_toBaselineOf;
        public static final int layout_constraintBottom_creator;
        public static final int layout_constraintBottom_toBottomOf;
        public static final int layout_constraintBottom_toTopOf;
        public static final int layout_constraintCircle;
        public static final int layout_constraintCircleAngle;
        public static final int layout_constraintCircleRadius;
        public static final int layout_constraintDimensionRatio;
        public static final int layout_constraintEnd_toEndOf;
        public static final int layout_constraintEnd_toStartOf;
        public static final int layout_constraintGuide_begin;
        public static final int layout_constraintGuide_end;
        public static final int layout_constraintGuide_percent;
        public static final int layout_constraintHeight_default;
        public static final int layout_constraintHeight_max;
        public static final int layout_constraintHeight_min;
        public static final int layout_constraintHeight_percent;
        public static final int layout_constraintHorizontal_bias;
        public static final int layout_constraintHorizontal_chainStyle;
        public static final int layout_constraintHorizontal_weight;
        public static final int layout_constraintLeft_creator;
        public static final int layout_constraintLeft_toLeftOf;
        public static final int layout_constraintLeft_toRightOf;
        public static final int layout_constraintRight_creator;
        public static final int layout_constraintRight_toLeftOf;
        public static final int layout_constraintRight_toRightOf;
        public static final int layout_constraintStart_toEndOf;
        public static final int layout_constraintStart_toStartOf;
        public static final int layout_constraintTop_creator;
        public static final int layout_constraintTop_toBottomOf;
        public static final int layout_constraintTop_toTopOf;
        public static final int layout_constraintVertical_bias;
        public static final int layout_constraintVertical_chainStyle;
        public static final int layout_constraintVertical_weight;
        public static final int layout_constraintWidth_default;
        public static final int layout_constraintWidth_max;
        public static final int layout_constraintWidth_min;
        public static final int layout_constraintWidth_percent;
        public static final int layout_editor_absoluteX;
        public static final int layout_editor_absoluteY;
        public static final int layout_goneMarginBottom;
        public static final int layout_goneMarginEnd;
        public static final int layout_goneMarginLeft;
        public static final int layout_goneMarginRight;
        public static final int layout_goneMarginStart;
        public static final int layout_goneMarginTop;
        public static final int layout_optimizationLevel;

        public attr() {
        }

        static {
            barrierAllowsGoneWidgets = R.attr.barrierAllowsGoneWidgets;
            barrierDirection = R.attr.barrierDirection;
            chainUseRtl = R.attr.chainUseRtl;
            constraintSet = R.attr.constraintSet;
            constraint_referenced_ids = R.attr.constraint_referenced_ids;
            content = R.attr.content;
            emptyVisibility = R.attr.emptyVisibility;
            layout_constrainedHeight = R.attr.layout_constrainedHeight;
            layout_constrainedWidth = R.attr.layout_constrainedWidth;
            layout_constraintBaseline_creator = R.attr.layout_constraintBaseline_creator;
            layout_constraintBaseline_toBaselineOf = R.attr.layout_constraintBaseline_toBaselineOf;
            layout_constraintBottom_creator = R.attr.layout_constraintBottom_creator;
            layout_constraintBottom_toBottomOf = R.attr.layout_constraintBottom_toBottomOf;
            layout_constraintBottom_toTopOf = R.attr.layout_constraintBottom_toTopOf;
            layout_constraintCircle = R.attr.layout_constraintCircle;
            layout_constraintCircleAngle = R.attr.layout_constraintCircleAngle;
            layout_constraintCircleRadius = R.attr.layout_constraintCircleRadius;
            layout_constraintDimensionRatio = R.attr.layout_constraintDimensionRatio;
            layout_constraintEnd_toEndOf = R.attr.layout_constraintEnd_toEndOf;
            layout_constraintEnd_toStartOf = R.attr.layout_constraintEnd_toStartOf;
            layout_constraintGuide_begin = R.attr.layout_constraintGuide_begin;
            layout_constraintGuide_end = R.attr.layout_constraintGuide_end;
            layout_constraintGuide_percent = R.attr.layout_constraintGuide_percent;
            layout_constraintHeight_default = R.attr.layout_constraintHeight_default;
            layout_constraintHeight_max = R.attr.layout_constraintHeight_max;
            layout_constraintHeight_min = R.attr.layout_constraintHeight_min;
            layout_constraintHeight_percent = R.attr.layout_constraintHeight_percent;
            layout_constraintHorizontal_bias = R.attr.layout_constraintHorizontal_bias;
            layout_constraintHorizontal_chainStyle = R.attr.layout_constraintHorizontal_chainStyle;
            layout_constraintHorizontal_weight = R.attr.layout_constraintHorizontal_weight;
            layout_constraintLeft_creator = R.attr.layout_constraintLeft_creator;
            layout_constraintLeft_toLeftOf = R.attr.layout_constraintLeft_toLeftOf;
            layout_constraintLeft_toRightOf = R.attr.layout_constraintLeft_toRightOf;
            layout_constraintRight_creator = R.attr.layout_constraintRight_creator;
            layout_constraintRight_toLeftOf = R.attr.layout_constraintRight_toLeftOf;
            layout_constraintRight_toRightOf = R.attr.layout_constraintRight_toRightOf;
            layout_constraintStart_toEndOf = R.attr.layout_constraintStart_toEndOf;
            layout_constraintStart_toStartOf = R.attr.layout_constraintStart_toStartOf;
            layout_constraintTop_creator = R.attr.layout_constraintTop_creator;
            layout_constraintTop_toBottomOf = R.attr.layout_constraintTop_toBottomOf;
            layout_constraintTop_toTopOf = R.attr.layout_constraintTop_toTopOf;
            layout_constraintVertical_bias = R.attr.layout_constraintVertical_bias;
            layout_constraintVertical_chainStyle = R.attr.layout_constraintVertical_chainStyle;
            layout_constraintVertical_weight = R.attr.layout_constraintVertical_weight;
            layout_constraintWidth_default = R.attr.layout_constraintWidth_default;
            layout_constraintWidth_max = R.attr.layout_constraintWidth_max;
            layout_constraintWidth_min = R.attr.layout_constraintWidth_min;
            layout_constraintWidth_percent = R.attr.layout_constraintWidth_percent;
            layout_editor_absoluteX = R.attr.layout_editor_absoluteX;
            layout_editor_absoluteY = R.attr.layout_editor_absoluteY;
            layout_goneMarginBottom = R.attr.layout_goneMarginBottom;
            layout_goneMarginEnd = R.attr.layout_goneMarginEnd;
            layout_goneMarginLeft = R.attr.layout_goneMarginLeft;
            layout_goneMarginRight = R.attr.layout_goneMarginRight;
            layout_goneMarginStart = R.attr.layout_goneMarginStart;
            layout_goneMarginTop = R.attr.layout_goneMarginTop;
            layout_optimizationLevel = R.attr.layout_optimizationLevel;
        }
    }
}
